# Generated by Django 4.2 on 2023-04-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_checkbox',
            field=models.BooleanField(default=False, verbose_name='Checkbox'),
        ),
    ]
