# Generated by Django 4.2 on 2023-04-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_question_is_checkbox_answer_is_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_checkbox',
        ),
        migrations.AddField(
            model_name='question',
            name='is_checkbox',
            field=models.BooleanField(default=False, verbose_name='Checkbox'),
        ),
    ]
