# Generated by Django 4.2 on 2023-04-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_answer_is_checkbox_question_is_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_checkbox',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('is_checkbox', 'Чекбокс'), ('is_start_rating', 'Звездный рейтинг'), ('is_range', 'Диапазон'), ('is_image_picker', 'Пикер')], default=1, max_length=25, verbose_name='Тип вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=6, verbose_name='Сложность'),
        ),
    ]
