# Generated by Django 4.2 on 2023-04-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_question_is_checkbox_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(verbose_name='Проходной балл'),
        ),
    ]
