# Generated by Django 4.2 on 2023-04-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_answer_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty_en',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=6, null=True, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty_ru',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=6, null=True, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Топик'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Топик'),
        ),
    ]
