# Generated by Django 4.2 on 2023-04-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_answer_text_en_answer_text_ru_question_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('is_checkbox', 'Чекбокс'), ('is_start_rating', 'Звездный рейтинг'), ('is_range', 'Диапазон'), ('is_image_picker', 'Пикер')], max_length=25, null=True, verbose_name='Тип вопроса'),
        ),
    ]
