# Generated by Django 4.2 on 2023-04-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty_en',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty_ru',
        ),
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.TextField(blank=True, null=True, verbose_name='Подсказга'),
        ),
    ]
