# Generated by Django 4.2 on 2023-04-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_quiz_difficulty_en_remove_quiz_difficulty_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказга'),
        ),
    ]
