# Generated by Django 4.2 on 2023-04-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_question_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='help_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказга'),
        ),
        migrations.AddField(
            model_name='question',
            name='help_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказга'),
        ),
    ]
