# Generated by Django 4.2 on 2023-04-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_quiz_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='topic_en',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='topic_ru',
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
