# Generated by Django 4.2 on 2023-04-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_result_easy_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='files/uploads', verbose_name='Обложка'),
        ),
    ]
